AWSTemplateFormatVersion: '2010-09-09'
Description: 'BeatMatchMe - Cognito User Pool for Authentication'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - production
    Description: Environment name

Resources:
  # Cognito User Pool
  BeatMatchMeUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub 'beatmatchme-users-${Environment}'
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      MfaConfiguration: OPTIONAL
      EnabledMfas:
        - SOFTWARE_TOKEN_MFA
      
      # Password Policy
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
          TemporaryPasswordValidityDays: 7
      
      # Email Configuration
      EmailConfiguration:
        EmailSendingAccount: COGNITO_DEFAULT
      
      # User Attributes Schema
      Schema:
        - Name: email
          AttributeDataType: String
          Required: true
          Mutable: false
        - Name: name
          AttributeDataType: String
          Required: true
          Mutable: true
        - Name: phone_number
          AttributeDataType: String
          Required: false
          Mutable: true
        - Name: role
          AttributeDataType: String
          Required: false
          Mutable: true
        - Name: tier
          AttributeDataType: String
          Required: false
          Mutable: true
      
      # Account Recovery
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
      
      # User Pool Tags
      UserPoolTags:
        Project: BeatMatchMe
        Environment: !Ref Environment

  # Performer User Group
  PerformersGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: performers
      Description: DJ/Performer users who create events
      UserPoolId: !Ref BeatMatchMeUserPool
      Precedence: 1

  # Audience User Group
  AudienceGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: audience
      Description: Audience members who make requests
      UserPoolId: !Ref BeatMatchMeUserPool
      Precedence: 2

  # Web App Client
  WebAppClient:
    Type: AWS::Cognito::UserPoolClient
    DependsOn:
      - GoogleIdentityProvider
      - FacebookIdentityProvider
      - AppleIdentityProvider
    Properties:
      ClientName: !Sub 'beatmatchme-web-${Environment}'
      UserPoolId: !Ref BeatMatchMeUserPool
      GenerateSecret: false
      RefreshTokenValidity: 30
      AccessTokenValidity: 60
      IdTokenValidity: 60
      TokenValidityUnits:
        RefreshToken: days
        AccessToken: minutes
        IdToken: minutes
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_PASSWORD_AUTH
      PreventUserExistenceErrors: ENABLED
      SupportedIdentityProviders:
        - COGNITO
        - Google
        - Facebook
        - SignInWithApple
      CallbackURLs:
        - http://localhost:5173
        - https://beatmatchme.com
      LogoutURLs:
        - http://localhost:5173
        - https://beatmatchme.com
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - email
        - openid
        - profile
      AllowedOAuthFlowsUserPoolClient: true
      ReadAttributes:
        - email
        - name
        - phone_number
        - custom:role
        - custom:tier
      WriteAttributes:
        - name
        - phone_number
        - custom:role
        - custom:tier

  # Google Identity Provider
  GoogleIdentityProvider:
    Type: AWS::Cognito::UserPoolIdentityProvider
    Properties:
      UserPoolId: !Ref BeatMatchMeUserPool
      ProviderName: Google
      ProviderType: Google
      ProviderDetails:
        client_id: REPLACE_WITH_GOOGLE_CLIENT_ID
        client_secret: REPLACE_WITH_GOOGLE_CLIENT_SECRET
        authorize_scopes: profile email openid
      AttributeMapping:
        email: email
        name: name
        picture: picture

  # Facebook Identity Provider
  FacebookIdentityProvider:
    Type: AWS::Cognito::UserPoolIdentityProvider
    Properties:
      UserPoolId: !Ref BeatMatchMeUserPool
      ProviderName: Facebook
      ProviderType: Facebook
      ProviderDetails:
        client_id: REPLACE_WITH_FACEBOOK_APP_ID
        client_secret: REPLACE_WITH_FACEBOOK_APP_SECRET
        authorize_scopes: public_profile,email
      AttributeMapping:
        email: email
        name: name
        picture: picture

  # Apple Identity Provider
  AppleIdentityProvider:
    Type: AWS::Cognito::UserPoolIdentityProvider
    Properties:
      UserPoolId: !Ref BeatMatchMeUserPool
      ProviderName: SignInWithApple
      ProviderType: SignInWithApple
      ProviderDetails:
        client_id: REPLACE_WITH_APPLE_SERVICE_ID
        team_id: REPLACE_WITH_APPLE_TEAM_ID
        key_id: REPLACE_WITH_APPLE_KEY_ID
        private_key: REPLACE_WITH_APPLE_PRIVATE_KEY
        authorize_scopes: name email
      AttributeMapping:
        email: email
        name: name

  # Mobile App Client
  MobileAppClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub 'beatmatchme-mobile-${Environment}'
      UserPoolId: !Ref BeatMatchMeUserPool
      GenerateSecret: false
      RefreshTokenValidity: 30
      AccessTokenValidity: 60
      IdTokenValidity: 60
      TokenValidityUnits:
        RefreshToken: days
        AccessToken: minutes
        IdToken: minutes
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_PASSWORD_AUTH
      PreventUserExistenceErrors: ENABLED

  # Identity Pool for AWS Resource Access
  IdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      IdentityPoolName: !Sub 'beatmatchme_identity_pool_${Environment}'
      AllowUnauthenticatedIdentities: false
      CognitoIdentityProviders:
        - ClientId: !Ref WebAppClient
          ProviderName: !GetAtt BeatMatchMeUserPool.ProviderName
        - ClientId: !Ref MobileAppClient
          ProviderName: !GetAtt BeatMatchMeUserPool.ProviderName

  # IAM Role for Authenticated Users
  CognitoAuthenticatedRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'beatmatchme-cognito-authenticated-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: cognito-identity.amazonaws.com
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                cognito-identity.amazonaws.com:aud: !Ref IdentityPool
              ForAnyValue:StringLike:
                cognito-identity.amazonaws.com:amr: authenticated
      Policies:
        - PolicyName: CognitoAuthenticatedPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                Resource:
                  - !Sub 'arn:aws:s3:::beatmatchme-${Environment}-assets/users/*'
              - Effect: Allow
                Action:
                  - appsync:GraphQL
                Resource:
                  - !Sub 'arn:aws:appsync:${AWS::Region}:${AWS::AccountId}:apis/*/types/*/fields/*'

  # Attach Role to Identity Pool
  IdentityPoolRoleAttachment:
    Type: AWS::Cognito::IdentityPoolRoleAttachment
    Properties:
      IdentityPoolId: !Ref IdentityPool
      Roles:
        authenticated: !GetAtt CognitoAuthenticatedRole.Arn

Outputs:
  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref BeatMatchMeUserPool
    Export:
      Name: !Sub '${AWS::StackName}-UserPoolId'

  UserPoolArn:
    Description: Cognito User Pool ARN
    Value: !GetAtt BeatMatchMeUserPool.Arn
    Export:
      Name: !Sub '${AWS::StackName}-UserPoolArn'

  WebAppClientId:
    Description: Web App Client ID
    Value: !Ref WebAppClient
    Export:
      Name: !Sub '${AWS::StackName}-WebAppClientId'

  MobileAppClientId:
    Description: Mobile App Client ID
    Value: !Ref MobileAppClient
    Export:
      Name: !Sub '${AWS::StackName}-MobileAppClientId'

  IdentityPoolId:
    Description: Identity Pool ID
    Value: !Ref IdentityPool
    Export:
      Name: !Sub '${AWS::StackName}-IdentityPoolId'

  PerformersGroupName:
    Description: Performers Group Name
    Value: !Ref PerformersGroup
    Export:
      Name: !Sub '${AWS::StackName}-PerformersGroup'

  AudienceGroupName:
    Description: Audience Group Name
    Value: !Ref AudienceGroup
    Export:
      Name: !Sub '${AWS::StackName}-AudienceGroup'
