AWSTemplateFormatVersion: '2010-09-09'
Description: 'BeatMatchMe - DynamoDB Tables'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - production
    Description: Environment name

Resources:
  # Users Table
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'beatmatchme-users-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: email-index
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: Project
          Value: BeatMatchMe
        - Key: Environment
          Value: !Ref Environment

  # Events Table
  EventsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'beatmatchme-events-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: eventId
          AttributeType: S
        - AttributeName: performerId
          AttributeType: S
        - AttributeName: startTime
          AttributeType: N
        - AttributeName: status
          AttributeType: S
      KeySchema:
        - AttributeName: eventId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: performerId-startTime-index
          KeySchema:
            - AttributeName: performerId
              KeyType: HASH
            - AttributeName: startTime
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: status-startTime-index
          KeySchema:
            - AttributeName: status
              KeyType: HASH
            - AttributeName: startTime
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: Project
          Value: BeatMatchMe
        - Key: Environment
          Value: !Ref Environment

  # Requests Table
  RequestsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'beatmatchme-requests-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: requestId
          AttributeType: S
        - AttributeName: eventId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
        - AttributeName: submittedAt
          AttributeType: N
        - AttributeName: status
          AttributeType: S
      KeySchema:
        - AttributeName: requestId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: eventId-submittedAt-index
          KeySchema:
            - AttributeName: eventId
              KeyType: HASH
            - AttributeName: submittedAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: userId-submittedAt-index
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: submittedAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: eventId-status-index
          KeySchema:
            - AttributeName: eventId
              KeyType: HASH
            - AttributeName: status
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: Project
          Value: BeatMatchMe
        - Key: Environment
          Value: !Ref Environment

  # Queues Table
  QueuesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'beatmatchme-queues-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: eventId
          AttributeType: S
      KeySchema:
        - AttributeName: eventId
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: Project
          Value: BeatMatchMe
        - Key: Environment
          Value: !Ref Environment

  # Transactions Table
  TransactionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'beatmatchme-transactions-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: transactionId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
        - AttributeName: eventId
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: N
      KeySchema:
        - AttributeName: transactionId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: userId-createdAt-index
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: eventId-createdAt-index
          KeySchema:
            - AttributeName: eventId
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: Project
          Value: BeatMatchMe
        - Key: Environment
          Value: !Ref Environment

  # Achievements Table
  AchievementsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'beatmatchme-achievements-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: Project
          Value: BeatMatchMe
        - Key: Environment
          Value: !Ref Environment

  # Group Requests Table
  GroupRequestsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'beatmatchme-group-requests-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: groupRequestId
          AttributeType: S
        - AttributeName: eventId
          AttributeType: S
        - AttributeName: status
          AttributeType: S
      KeySchema:
        - AttributeName: groupRequestId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: eventId-status-index
          KeySchema:
            - AttributeName: eventId
              KeyType: HASH
            - AttributeName: status
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: expiresAt
        Enabled: true
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: Project
          Value: BeatMatchMe
        - Key: Environment
          Value: !Ref Environment

Outputs:
  UsersTableName:
    Description: Users Table Name
    Value: !Ref UsersTable
    Export:
      Name: !Sub '${AWS::StackName}-UsersTable'

  UsersTableArn:
    Description: Users Table ARN
    Value: !GetAtt UsersTable.Arn
    Export:
      Name: !Sub '${AWS::StackName}-UsersTableArn'

  UsersTableStreamArn:
    Description: Users Table Stream ARN
    Value: !GetAtt UsersTable.StreamArn
    Export:
      Name: !Sub '${AWS::StackName}-UsersTableStreamArn'

  EventsTableName:
    Description: Events Table Name
    Value: !Ref EventsTable
    Export:
      Name: !Sub '${AWS::StackName}-EventsTable'

  EventsTableArn:
    Description: Events Table ARN
    Value: !GetAtt EventsTable.Arn
    Export:
      Name: !Sub '${AWS::StackName}-EventsTableArn'

  EventsTableStreamArn:
    Description: Events Table Stream ARN
    Value: !GetAtt EventsTable.StreamArn
    Export:
      Name: !Sub '${AWS::StackName}-EventsTableStreamArn'

  RequestsTableName:
    Description: Requests Table Name
    Value: !Ref RequestsTable
    Export:
      Name: !Sub '${AWS::StackName}-RequestsTable'

  RequestsTableArn:
    Description: Requests Table ARN
    Value: !GetAtt RequestsTable.Arn
    Export:
      Name: !Sub '${AWS::StackName}-RequestsTableArn'

  RequestsTableStreamArn:
    Description: Requests Table Stream ARN
    Value: !GetAtt RequestsTable.StreamArn
    Export:
      Name: !Sub '${AWS::StackName}-RequestsTableStreamArn'

  QueuesTableName:
    Description: Queues Table Name
    Value: !Ref QueuesTable
    Export:
      Name: !Sub '${AWS::StackName}-QueuesTable'

  QueuesTableArn:
    Description: Queues Table ARN
    Value: !GetAtt QueuesTable.Arn
    Export:
      Name: !Sub '${AWS::StackName}-QueuesTableArn'

  TransactionsTableName:
    Description: Transactions Table Name
    Value: !Ref TransactionsTable
    Export:
      Name: !Sub '${AWS::StackName}-TransactionsTable'

  TransactionsTableArn:
    Description: Transactions Table ARN
    Value: !GetAtt TransactionsTable.Arn
    Export:
      Name: !Sub '${AWS::StackName}-TransactionsTableArn'

  AchievementsTableName:
    Description: Achievements Table Name
    Value: !Ref AchievementsTable
    Export:
      Name: !Sub '${AWS::StackName}-AchievementsTable'

  GroupRequestsTableName:
    Description: Group Requests Table Name
    Value: !Ref GroupRequestsTable
    Export:
      Name: !Sub '${AWS::StackName}-GroupRequestsTable'
