// AWS Configuration for BeatMatchMe
// Auto-generated by create-app-client.ps1

const awsconfig = {
  Auth: {
    Cognito: {
      userPoolId: 'us-east-1_m1PhjZ4yD',
      userPoolClientId: '48ledus0f1muv2p36ko0815s7g',
      region: 'us-east-1',
      loginWith: {
        email: true,
      },
      signUpVerificationMethod: 'code',
      userAttributes: {
        email: {
          required: true,
        },
        name: {
          required: true,
        },
      },
      passwordFormat: {
        minLength: 8,
        requireLowercase: true,
        requireUppercase: true,
        requireNumbers: true,
        requireSpecialCharacters: false,
      },
    },
  },
  API: {
    GraphQL: {
      endpoint: 'https://v7emm7lqsjbkvoligy4udwru6i.appsync-api.us-east-1.amazonaws.com/graphql',
      region: 'us-east-1',
      defaultAuthMode: 'userPool' as const,
    },
  },
  Storage: {
    S3: {
      bucket: 'beatmatchme-assets-2407',
      region: 'us-east-1',
    },
  },
};

export default awsconfig;
